/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BattleshipJNI */

#ifndef _Included_BattleshipJNI
#define _Included_BattleshipJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BattleshipJNI
 * Method:    PlaceShip
 * Signature: (Ljava/lang/String;[II)I
 */
JNIEXPORT jint JNICALL Java_BattleshipJNI_PlaceShip
  (JNIEnv *, jobject, jstring, jintArray, jint);

/*
 * Class:     BattleshipJNI
 * Method:    Attack
 * Signature: ([ILBattleshipJNI;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BattleshipJNI_Attack
  (JNIEnv *, jobject, jintArray, jobject);

/*
 * Class:     BattleshipJNI
 * Method:    HasLost
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_BattleshipJNI_HasLost
  (JNIEnv *, jobject);

/*
 * Class:     BattleshipJNI
 * Method:    printSelfGrid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BattleshipJNI_printSelfGrid
  (JNIEnv *, jobject);

/*
 * Class:     BattleshipJNI
 * Method:    printTargetGrid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BattleshipJNI_printTargetGrid
  (JNIEnv *, jobject);

/*
 * Class:     BattleshipJNI
 * Method:    printGridsSideBySide
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BattleshipJNI_printGridsSideBySide
  (JNIEnv *, jobject);

/*
 * Class:     BattleshipJNI
 * Method:    initializePlayer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_BattleshipJNI_initializePlayer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
